{"level":"error","message":"MongoDB Connection Error: Can't call `openUri()` on an active connection with different connection strings. Make sure you aren't calling `mongoose.connect()` multiple times. See: https://mongoosejs.com/docs/connections.html#multiple_connections","stack":"MongooseError: Can't call `openUri()` on an active connection with different connection strings. Make sure you aren't calling `mongoose.connect()` multiple times. See: https://mongoosejs.com/docs/connections.html#multiple_connections\n    at NativeConnection.createClient (C:\\Users\\FOLTI-ADMIN\\Documents\\Ambitious_data\\VTU\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\connection.js:239:13)\n    at NativeConnection.openUri (C:\\Users\\FOLTI-ADMIN\\Documents\\Ambitious_data\\VTU\\node_modules\\mongoose\\lib\\connection.js:1016:34)\n    at Mongoose.connect (C:\\Users\\FOLTI-ADMIN\\Documents\\Ambitious_data\\VTU\\node_modules\\mongoose\\lib\\mongoose.js:446:15)\n    at connectDB (C:\\Users\\FOLTI-ADMIN\\Documents\\Ambitious_data\\VTU\\src\\config\\database.ts:34:20)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2025-03-16T11:01:51.388Z"}
{"level":"error","message":"MongoDB Connection Error: Can't call `openUri()` on an active connection with different connection strings. Make sure you aren't calling `mongoose.connect()` multiple times. See: https://mongoosejs.com/docs/connections.html#multiple_connections","stack":"MongooseError: Can't call `openUri()` on an active connection with different connection strings. Make sure you aren't calling `mongoose.connect()` multiple times. See: https://mongoosejs.com/docs/connections.html#multiple_connections\n    at NativeConnection.createClient (C:\\Users\\FOLTI-ADMIN\\Documents\\Ambitious_data\\VTU\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\connection.js:239:13)\n    at NativeConnection.openUri (C:\\Users\\FOLTI-ADMIN\\Documents\\Ambitious_data\\VTU\\node_modules\\mongoose\\lib\\connection.js:1016:34)\n    at Mongoose.connect (C:\\Users\\FOLTI-ADMIN\\Documents\\Ambitious_data\\VTU\\node_modules\\mongoose\\lib\\mongoose.js:446:15)\n    at connectDB (C:\\Users\\FOLTI-ADMIN\\Documents\\Ambitious_data\\VTU\\src\\config\\database.ts:34:20)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2025-03-16T11:26:47.689Z"}
{"level":"error","message":"MongoDB Connection Error: Can't call `openUri()` on an active connection with different connection strings. Make sure you aren't calling `mongoose.connect()` multiple times. See: https://mongoosejs.com/docs/connections.html#multiple_connections","stack":"MongooseError: Can't call `openUri()` on an active connection with different connection strings. Make sure you aren't calling `mongoose.connect()` multiple times. See: https://mongoosejs.com/docs/connections.html#multiple_connections\n    at NativeConnection.createClient (C:\\Users\\FOLTI-ADMIN\\Documents\\Ambitious_data\\VTU\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\connection.js:239:13)\n    at NativeConnection.openUri (C:\\Users\\FOLTI-ADMIN\\Documents\\Ambitious_data\\VTU\\node_modules\\mongoose\\lib\\connection.js:1016:34)\n    at Mongoose.connect (C:\\Users\\FOLTI-ADMIN\\Documents\\Ambitious_data\\VTU\\node_modules\\mongoose\\lib\\mongoose.js:446:15)\n    at connectDB (C:\\Users\\FOLTI-ADMIN\\Documents\\Ambitious_data\\VTU\\src\\config\\database.ts:34:20)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2025-03-16T11:28:28.065Z"}
{"error":{"ErrorCodes":"Email not verified","isOperational":true,"statusCode":401},"level":"error","message":"[Global Error Handler] Please verify your email address first","method":"POST","path":"/api/v1/login","stack":"Error: Please verify your email address first\n    at AuthController.login (C:\\Users\\FOLTI-ADMIN\\Documents\\Ambitious_data\\VTU\\src\\controllers\\authController.ts:179:15)","timestamp":"2025-03-16T11:31:42.824Z"}
{"error":{"ErrorCodes":"Email not verified","isOperational":true,"statusCode":401},"level":"error","message":"[Global Error Handler] Please verify your email address first","method":"POST","path":"/api/v1/login","stack":"Error: Please verify your email address first\n    at AuthController.login (C:\\Users\\FOLTI-ADMIN\\Documents\\Ambitious_data\\VTU\\src\\controllers\\authController.ts:179:15)","timestamp":"2025-03-16T11:35:03.973Z"}
{"code":"ESOCKET","command":"CONN","level":"error","library":"SSL routines","message":"Email service connection failed: D4580000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:c:\\ws\\deps\\openssl\\openssl\\ssl\\record\\ssl3_record.c:355:\n D4580000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:c:\\ws\\deps\\openssl\\openssl\\ssl\\record\\ssl3_record.c:355:\n","reason":"wrong version number","stack":"Error: D4580000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:c:\\ws\\deps\\openssl\\openssl\\ssl\\record\\ssl3_record.c:355:\n","timestamp":"2025-03-16T12:26:51.853Z"}
{"level":"error","message":"Unhandled Rejection at:","timestamp":"2025-03-16T12:26:51.854Z"}
{"code":"EAUTH","command":"AUTH PLAIN","level":"error","message":"Email service connection failed: Invalid login: 535 5.7.8 Authentication failed Invalid login: 535 5.7.8 Authentication failed","response":"535 5.7.8 Authentication failed","responseCode":535,"stack":"Error: Invalid login: 535 5.7.8 Authentication failed\n    at SMTPConnection._formatError (C:\\Users\\FOLTI-ADMIN\\Documents\\Ambitious_data\\VTU\\node_modules\\nodemailer\\lib\\smtp-connection\\index.js:807:19)\n    at SMTPConnection._actionAUTHComplete (C:\\Users\\FOLTI-ADMIN\\Documents\\Ambitious_data\\VTU\\node_modules\\nodemailer\\lib\\smtp-connection\\index.js:1586:34)\n    at SMTPConnection.<anonymous> (C:\\Users\\FOLTI-ADMIN\\Documents\\Ambitious_data\\VTU\\node_modules\\nodemailer\\lib\\smtp-connection\\index.js:554:26)\n    at SMTPConnection._processResponse (C:\\Users\\FOLTI-ADMIN\\Documents\\Ambitious_data\\VTU\\node_modules\\nodemailer\\lib\\smtp-connection\\index.js:991:20)\n    at SMTPConnection._onData (C:\\Users\\FOLTI-ADMIN\\Documents\\Ambitious_data\\VTU\\node_modules\\nodemailer\\lib\\smtp-connection\\index.js:772:14)\n    at TLSSocket.SMTPConnection._onSocketData (C:\\Users\\FOLTI-ADMIN\\Documents\\Ambitious_data\\VTU\\node_modules\\nodemailer\\lib\\smtp-connection\\index.js:195:44)\n    at TLSSocket.emit (node:events:519:28)\n    at TLSSocket.emit (node:domain:488:12)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-03-16T12:35:21.895Z"}
{"level":"error","message":"Unhandled Rejection at:","timestamp":"2025-03-16T12:35:21.897Z"}
{"error":{"ErrorCodes":"User already exist","isOperational":true,"statusCode":400},"level":"error","message":"[Global Error Handler] Email already registered","method":"POST","path":"/api/v1/register","stack":"Error: Email already registered\n    at AuthController.register (C:\\Users\\FOLTI-ADMIN\\Documents\\Ambitious_data\\VTU\\src\\controllers\\authController.ts:111:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2025-03-16T13:42:39.191Z"}
